First commit (Revise by NCU)

diff --git a/cmake_targets/tools/build_helper b/cmake_targets/tools/build_helper
--- a/cmake_targets/tools/build_helper
+++ b/cmake_targets/tools/build_helper
@@ -337,132 +337,135 @@ install_protobuf_c() {
 }
 
 install_usrp_uhd_driver_from_source(){
-    uhd_install_log=$OPENAIR_DIR/cmake_targets/log/uhd_install_log.txt
-    echo_info "\nInstalling UHD driver from sources. The log file for UHD driver installation is here: $uhd_install_log "
-    (
-    pushd /tmp
-    echo "Cloning UHD driver repository"
-    rm -rf /tmp/uhd
-    git clone https://github.com/EttusResearch/uhd.git
-    cd uhd
-    if [[ -v UHD_VERSION ]]; then
-        git checkout tags/v${UHD_VERSION}
-    else
-        git checkout tags/v4.0.0.0
-    fi
-    mkdir -p host/build
-    cd host/build || true
-    $CMAKE ../ -GNinja
-    echo "Compiling UHD"
-    ninja
-    $SUDO ninja install
-    $SUDO ldconfig -v
-    if [ $IS_CONTAINER -eq 0 ]; then
-        if [[ "$OS_DISTRO" == "ubuntu" ]]; then
-            $SUDO /usr/local/lib/uhd/utils/uhd_images_downloader.py
-        fi
-        if [[ "$OS_DISTRO" == "rhel" ]]; then
-            $SUDO /usr/local/lib64/uhd/utils/uhd_images_downloader.py
-        fi
-    fi
-    popd
-    rm -rf /tmp/uhd
-    ) >& $uhd_install_log
+  echo "install_usrp_uhd_driver_from_source"
+    # uhd_install_log=$OPENAIR_DIR/cmake_targets/log/uhd_install_log.txt
+    # echo_info "\nInstalling UHD driver from sources. The log file for UHD driver installation is here: $uhd_install_log "
+    # (
+    # pushd /tmp
+    # echo "Cloning UHD driver repository"
+    # rm -rf /tmp/uhd
+    # git clone https://github.com/EttusResearch/uhd.git
+    # cd uhd
+    # if [[ -v UHD_VERSION ]]; then
+    #     git checkout tags/v${UHD_VERSION}
+    # else
+    #     git checkout tags/v4.0.0.0
+    # fi
+  
+    # cd host/build || true
+    # $CMAKE ../ -GNinja
+    # echo "Compiling UHD"
+    # ninja
+    # $SUDO ninja install
+    # $SUDO ldconfig -v
+    # if [ $IS_CONTAINER -eq 0 ]; then
+    #     if [[ "$OS_DISTRO" == "ubuntu" ]]; then
+    #         $SUDO /usr/local/lib/uhd/utils/uhd_images_downloader.py
+    #     fi
+    #     if [[ "$OS_DISTRO" == "rhel" ]]; then
+    #         $SUDO /usr/local/lib64/uhd/utils/uhd_images_downloader.py
+    #     fi
+    # fi
+    # popd
+    # rm -rf /tmp/uhd
+    # ) >& $uhd_install_log
 }
 
 check_install_usrp_uhd_driver(){
-    if [[ "$OS_DISTRO" == "ubuntu" ]]; then
-        #first we remove old installation
-        $SUDO apt-get remove uhd -y || true
-        $SUDO apt-get remove uhd-host -y || true
-        $SUDO apt-get remove libuhd-dev -y || true
-        $SUDO apt-get remove libuhd003 -y || true
-        $SUDO apt-get remove libuhd3.13.1 -y || true
-        $SUDO apt-get remove libuhd3.14.0 -y || true
-        $SUDO apt-get remove libuhd3.14.1 -y || true
-        $SUDO apt-get remove libuhd3.15.0 -y || true
-        local distribution=$(get_distribution_release)
-        if [[ "$distribution" == "ubuntu18.04" || "$distribution" == "ubuntu20.04" || "$distribution" == "ubuntu22.04" ]]; then
-            $SUDO apt-get remove libuhd4.0.0 -y || true
-            $SUDO apt-get remove libuhd4.1.0 -y || true
-        fi
-        v=$(lsb_release -cs)
-        $SUDO apt-add-repository --remove "deb http://files.ettus.com/binaries/uhd/repo/uhd/ubuntu/$v $v main"
-        if [[ -v BUILD_UHD_FROM_SOURCE ]]; then
-            $SUDO apt-get install -y libboost-all-dev libusb-1.0-0-dev doxygen python3-docutils python3-mako python3-numpy python3-requests python3-setuptools ninja-build
-            install_usrp_uhd_driver_from_source
-            return
-        fi
-        # The new USRP repository
-        # Raphael Defosseux: Adding a loop on adding PPA because in CI the gpg key retrieve may
-        # timeout due to proxy / network latencies in Eurecom on VM
-        echo_info "\nAdding PPA repository ettusresearch/uhd\n"
-        x=0
-        while [ $x -le 5 ]
-        do
-            if $SUDO add-apt-repository ppa:ettusresearch/uhd -y
-            then
-                echo_info "add-apt-repository successful\n"
-                break
-            else
-                echo_info "add-apt-repository failed, retrying...\n"
-                sleep 30
-            fi
-            x=$((x + 1))
-        done
-        $SUDO apt-get update
-        $SUDO apt-get -y install python-tk libboost-all-dev libusb-1.0-0-dev
-        case "$(get_distribution_release)" in
-          "ubuntu16.04")
-            $SUDO apt-get -y install libuhd-dev libuhd3.15.0 uhd-host
-            ;;
-          "ubuntu18.04" | "ubuntu20.04" | "ubuntu22.04")
-            $SUDO apt-get -y install libuhd-dev libuhd4.2.0 uhd-host
-            ;;
-        esac
-    elif [[ "$OS_BASEDISTRO" == "fedora" ]]; then
-        if [ $IS_CONTAINER -eq 0 ]
-        then
-            $SUDO $INSTALLER -y install python boost libusb-devel libusbx-devel boost-devel python-mako python-docutils $CMAKE
-            $SUDO -H pip install requests
-        else
-            $SUDO $INSTALLER -y install boost boost-devel $CMAKE
-            $SUDO pip3 install mako requests
-        fi
-        if [[ "$OS_DISTRO" == "rhel" ]] || [[ "$OS_DISTRO" == "centos" ]]; then
-            if [ $IS_CONTAINER -eq 0 ]
-            then
-                # until EPEL repo hasn't bumped UHD driver to >=3.10 in EPEL, build driver from source
-                $SUDO $INSTALLER -y remove uhd uhd-devel uhd-firmware
-            fi
-            install_usrp_uhd_driver_from_source
-        else
-            $SUDO $INSTALLER -y install uhd uhd-devel uhd-firmware
-        fi
-    fi
+  echo "check_install_usrp_uhd_driver"
+    # if [[ "$OS_DISTRO" == "ubuntu" ]]; then
+    #     #first we remove old installation
+    #     $SUDO apt-get remove uhd -y || true
+    #     $SUDO apt-get remove uhd-host -y || true
+    #     $SUDO apt-get remove libuhd-dev -y || true
+    #     $SUDO apt-get remove libuhd003 -y || true
+    #     $SUDO apt-get remove libuhd3.13.1 -y || true
+    #     $SUDO apt-get remove libuhd3.14.0 -y || true
+    #     $SUDO apt-get remove libuhd3.14.1 -y || true
+    #     $SUDO apt-get remove libuhd3.15.0 -y || true
+    #     local distribution=$(get_distribution_release)
+    #     if [[ "$distribution" == "ubuntu18.04" || "$distribution" == "ubuntu20.04" || "$distribution" == "ubuntu22.04" ]]; then
+    #         $SUDO apt-get remove libuhd4.0.0 -y || true
+    #         $SUDO apt-get remove libuhd4.1.0 -y || true
+    #     fi
+    #     v=$(lsb_release -cs)
+    #     $SUDO apt-add-repository --remove "deb http://files.ettus.com/binaries/uhd/repo/uhd/ubuntu/$v $v main"
+    #     if [[ -v BUILD_UHD_FROM_SOURCE ]]; then
+    #         $SUDO apt-get install -y libboost-all-dev libusb-1.0-0-dev doxygen python3-docutils python3-mako python3-numpy python3-requests python3-setuptools ninja-build
+    #         install_usrp_uhd_driver_from_source
+    #         return
+    #     fi
+    #     # The new USRP repository
+    #     # Raphael Defosseux: Adding a loop on adding PPA because in CI the gpg key retrieve may
+    #     # timeout due to proxy / network latencies in Eurecom on VM
+    #     echo_info "\nAdding PPA repository ettusresearch/uhd\n"
+    #     x=0
+    #     while [ $x -le 5 ]
+    #     do
+    #         if $SUDO add-apt-repository ppa:ettusresearch/uhd -y
+    #         then
+    #             echo_info "add-apt-repository successful\n"
+    #             break
+    #         else
+    #             echo_info "add-apt-repository failed, retrying...\n"
+    #             sleep 30
+    #         fi
+    #         x=$((x + 1))
+    #     done
+    #     $SUDO apt-get update
+    #     $SUDO apt-get -y install python-tk libboost-all-dev libusb-1.0-0-dev
+    #     case "$(get_distribution_release)" in
+    #       "ubuntu16.04")
+    #         $SUDO apt-get -y install libuhd-dev libuhd3.15.0 uhd-host
+    #         ;;
+    #       "ubuntu18.04" | "ubuntu20.04" | "ubuntu22.04")
+    #         $SUDO apt-get -y install libuhd-dev libuhd4.2.0 uhd-host
+    #         ;;
+    #     esac
+    # elif [[ "$OS_BASEDISTRO" == "fedora" ]]; then
+    #     if [ $IS_CONTAINER -eq 0 ]
+    #     then
+    #         $SUDO $INSTALLER -y install python boost libusb-devel libusbx-devel boost-devel python-mako python-docutils $CMAKE
+    #         $SUDO -H pip install requests
+    #     else
+    #         $SUDO $INSTALLER -y install boost boost-devel $CMAKE
+    #         $SUDO pip3 install mako requests
+    #     fi
+    #     if [[ "$OS_DISTRO" == "rhel" ]] || [[ "$OS_DISTRO" == "centos" ]]; then
+    #         if [ $IS_CONTAINER -eq 0 ]
+    #         then
+    #             # until EPEL repo hasn't bumped UHD driver to >=3.10 in EPEL, build driver from source
+    #             $SUDO $INSTALLER -y remove uhd uhd-devel uhd-firmware
+    #         fi
+    #         install_usrp_uhd_driver_from_source
+    #     else
+    #         $SUDO $INSTALLER -y install uhd uhd-devel uhd-firmware
+    #     fi
+    # fi
 }
 
 install_usrp_uhd_driver() {
-    if [[ "$OS_DISTRO" == "ubuntu" ]]; then
-        # We move uhd-host apart because it depends on linux kernel version
-        # On newer kernels, it fails to install
-        $SUDO apt-get -y install uhd-host
-    fi
-    # quick workaround for RHE7.6
-    local distribution=$(get_distribution_release)
-    if [ -z $1 ]; then
-      if [[ "$OS_DISTRO" == "rhel" ]]; then
-          $SUDO /usr/local/bin/uhd_images_downloader
-      else
-          $SUDO uhd_images_downloader
-      fi
-    else
-      if [[ "$OS_DISTRO" == "rhel" ]]; then
-          $SUDO /usr/local/bin/uhd_images_downloader -i $1
-      else
-          $SUDO uhd_images_downloader -i $1
-      fi
-    fi
+  echo "install_usrp_uhd_driver"
+    # if [[ "$OS_DISTRO" == "ubuntu" ]]; then
+    #     # We move uhd-host apart because it depends on linux kernel version
+    #     # On newer kernels, it fails to install
+    #     $SUDO apt-get -y install uhd-host
+    # fi
+    # # quick workaround for RHE7.6
+    # local distribution=$(get_distribution_release)
+    # if [ -z $1 ]; then
+    #   if [[ "$OS_DISTRO" == "rhel" ]]; then
+    #       $SUDO /usr/local/bin/uhd_images_downloader
+    #   else
+    #       $SUDO uhd_images_downloader
+    #   fi
+    # else
+    #   if [[ "$OS_DISTRO" == "rhel" ]]; then
+    #       $SUDO /usr/local/bin/uhd_images_downloader -i $1
+    #   else
+    #       $SUDO uhd_images_downloader -i $1
+    #   fi
+    # fi
 }
 
 install_bladerf_driver_from_source(){
